spring:
  application:
    name: nomegenerator
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:nomegenerator}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${PORT:8080}
