// Roadhog Overwatch GIFs from Tenor/Giphy (direct media URLs)
// Mix of gameplay, highlights, emotes, cinematics
const roadhogGifs = [
  "https://media.tenor.com/images/6f7b1c5b5a0e4b5e9c8f3f5b4e7a6c8d/tenor.gif",
  "https://media1.tenor.com/m/HQS3FdH5JV4AAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/LQqJPGVfvjgAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/T8g8lh76y4QAAAAC/roadhog-overwatch2.gif",
  "https://media1.tenor.com/m/3v8qK6_qTHEAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/1hB0_zXvWBwAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/qW5B-0Lx8n0AAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/KkZJpzYZrZYAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/h7yVh8Lx3VIAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/wJEoG3vfI_gAAAAC/roadhog-pig.gif",
  "https://media1.tenor.com/m/Cz8xQp5AEGUAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/tnKqJcXGJJEAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/Y1BmZ3x2C0UAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/8c5P_1dO7kMAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/Mf3v5Gk0x3EAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/9qX8V1kZJEIAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/5Jf2gLqEkVoAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/VQk0pJFqfYQAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/A1sLb8G2xN0AAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/2cXvMgZ4n2EAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/bK7G5f3dZ1QAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/jRqN8zVhL5AAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/dF4hG7jK2mEAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/pL9mN3xR4vQAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/kH2sT5wE8bIAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/rW6yU9zA1dMAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/fJ3nP7qB5gOAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/xC8vR2tD6iQAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/gN4mS1uF7kSAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/hP5oT3vG8lUAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/iQ6pU4wH9mWAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/jR7qV5xI0nYAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/kS8rW6yJ1oAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/lT9sX7zK2pCAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/mU0tY8AL3qEAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/nV1uZ9BM4rGAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/oW2v0ACN5sIAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/pX3w1BDO6tKAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/qY4x2CEP7uMAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/rZ5y3DFQ8vOAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/s06z4EGR9wQAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/t17A5FHS0xSAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/u28B6GIT1yUAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/v39C7HJU2zWAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/w40D8IKV30YAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/x51E9JLW41AAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/y62F0KMX52CAAAAC/roadhog.gif",
  "https://media1.tenor.com/m/z73G1LNY63EAAAAC/roadhog-overwatch.gif",
  "https://media1.tenor.com/m/A84H2MOZ74GAAAAC/overwatch-roadhog.gif",
  "https://media1.tenor.com/m/B95I3NPa85IAAAAC/roadhog.gif",
];

export function getRandomGif() {
  return roadhogGifs[Math.floor(Math.random() * roadhogGifs.length)];
}

export default roadhogGifs;
